// plugins/fontawesome.ts
import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

// 导入需要的图标
import {
  faHome,
  faUser,
  faPlus,
  faEye,
  faEyeSlash,
  faArrowLeft,
  faSearch,
  faWifi,
  faBatteryFull,
  faSignal,
  faHeart,
  faCog,
  faShoppingCart,
  faMapMarkerAlt,
  faCalendar,
  faPhone,
  faBars,
  faTimes,
  faChevronRight,
  faChevronLeft,
  faChevronDown,
  faChevronUp,
  faBell,
  faMap,
  faUsers,
  //faCastle,
  faBuilding,
  faPlayCircle,
  faCheckCircle,
  faClock,
  faStar,
  faImage,
  faLock,
  faMountain,
  faStore,
  faChurch,
  faTheaterMasks,
  faUtensils,
  faGraduationCap,
  faTree,
  faCamera,
  faGamepad,
  faMusic,
  faBookOpen,
  faDumbbell,
  faPalette,
  faFireFlameCurved,
  faLocationDot,
  faGlobe,
  faCompass,
  faRoute,
  faFlag,
  faAward,
  faTrophy,
  faGift,
  faTicketAlt,
  faCalendarAlt,
  faClipboard,
  faEdit,
  faTrash,
  faDownload,
  faUpload,
  faShare,
  faQrcode,
  faHeadphones,
  faMicrophone,
  faVolumeUp,
  faVolumeMute,
  faVideo,
  faFilm,
  faExpandArrowsAlt,
  faCompressArrowsAlt,
  faCloud,
  //faHomeSolid,
  faQuestionCircle,
  faFire,
  faDice,
  //faCloud,
  //faHome as faHomeSolid
} from '@fortawesome/free-solid-svg-icons'

import {
  faHeart as faHeartRegular,
  faUser as faUserRegular,
  //faHome as faHomeRegular,
  faCalendar as faCalendarRegular,
  faComments as faCommentsRegular,
  faBell as faBellRegular,
  faBookmark as faBookmarkRegular,
  faStar as faStarRegular,
  faThumbsUp as faThumbsUpRegular,
  faEye as faEyeRegular,
  faClock as faClockRegular
} from '@fortawesome/free-regular-svg-icons'

// 添加图标到库
library.add(
  // Solid icons
  faHome,
  faUser,
  faPlus,
  faEye,
  faEyeSlash,
  faArrowLeft,
  faSearch,
  faWifi,
  faBatteryFull,
  faSignal,
  faHeart,
  faCog,
  faShoppingCart,
  faMapMarkerAlt,
  faCalendar,
  faPhone,
  faBars,
  faTimes,
  faChevronRight,
  faChevronLeft,
  faChevronDown,
  faChevronUp,
  faBell,
  faMap,
  faUsers,
  //faCastle,
  faBuilding,
  faPlayCircle,
  faCheckCircle,
  faClock,
  faStar,
  faImage,
  faLock,
  faMountain,
  faStore,
  faChurch,
  faTheaterMasks,
  faUtensils,
  faGraduationCap,
  faTree,
  faCamera,
  faGamepad,
  faMusic,
  faBookOpen,
  faDumbbell,
  faPalette,
  faFireFlameCurved,
  faLocationDot,
  faGlobe,
  faCompass,
  faRoute,
  faFlag,
  faAward,
  faTrophy,
  faGift,
  faTicketAlt,
  faCalendarAlt,
  faClipboard,
  faEdit,
  faTrash,
  faDownload,
  faUpload,
  faShare,
  faQrcode,
  faHeadphones,
  faMicrophone,
  faVolumeUp,
  faVolumeMute,
  faVideo,
  faFilm,
  faExpandArrowsAlt,
  faCompressArrowsAlt,
  
  // Regular icons
  faHeartRegular,
  faUserRegular,
  //faHomeRegular,
  faCalendarRegular,
  faCommentsRegular,
  faBellRegular,
  faBookmarkRegular,
  faStarRegular,
  faThumbsUpRegular,
  faEyeRegular,
  faClockRegular
)

export { FontAwesomeIcon }